### ISSUE TITLE
Do you have example slides

### ISSUE THREAD

**Issue by veso266** [mpetroff/beamer-theme-matrix#1]
Hi there, I am trying to create something like this: https://hartwork.org/beamer-theme-matrix/all/beamer-beetle-Darmstadt-0.png

got the theme but am unable to create TOC with bullets in header, so do you have rmd slides that are on this picture?

Thanks

**Comment by mpetroff** [comment]
Please read the repository description before posting. This repository is associated with the mpetroff.net Beamer theme matrix, not the hartwork.org one. As it is unaffiliated with the hartwork.org version, I don't have any files for it.
